using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ZeroAlloc.Collections.Generators;

[Generator]
public sealed class PooledCollectionGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "ZeroAlloc.Collections.PooledCollectionAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targets = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeFullName,
            predicate: static (node, _) => node is TypeDeclarationSyntax,
            transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!.Value);

        context.RegisterSourceOutput(targets, static (spc, model) => Execute(spc, model));
    }

    private static GeneratorModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        var typeSymbol = (INamedTypeSymbol)ctx.TargetSymbol;
        var attr = ctx.Attributes.FirstOrDefault(a =>
            a.AttributeClass?.ToDisplayString() == AttributeFullName);

        if (attr is null || attr.ConstructorArguments.Length == 0)
            return null;

        var elementType = attr.ConstructorArguments[0].Value as INamedTypeSymbol;
        if (elementType is null)
            return null;

        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : typeSymbol.ContainingNamespace.ToDisplayString();

        return new GeneratorModel(
            Namespace: ns,
            TypeName: typeSymbol.Name,
            ElementTypeFullName: elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            IsStruct: typeSymbol.IsValueType,
            Accessibility: typeSymbol.DeclaredAccessibility);
    }

    private static void Execute(SourceProductionContext spc, GeneratorModel model)
    {
        var accessibility = model.Accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Private => "private",
            _ => "internal"
        };

        var typeKind = model.IsStruct ? "struct" : "class";
        var readonlyMod = model.IsStruct ? "readonly " : "";
        var T = model.ElementTypeFullName;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");
        }

        var indent = model.Namespace is not null ? "    " : "";
        var indent2 = indent + "    ";
        var indent3 = indent2 + "    ";
        var indent4 = indent3 + "    ";

        sb.AppendLine($"{indent}{accessibility} partial {typeKind} {model.TypeName} : System.IDisposable");
        sb.AppendLine($"{indent}{{");

        // Fields
        sb.AppendLine($"{indent2}private {T}[]? _items;");
        sb.AppendLine($"{indent2}private int _count;");
        sb.AppendLine($"{indent2}private ArrayPool<{T}>? _pool;");
        sb.AppendLine();
        sb.AppendLine($"{indent2}private const int DefaultCapacity = 4;");
        sb.AppendLine();

        // Default constructor
        sb.AppendLine($"{indent2}/// <summary>Creates a new empty pooled collection using the shared pool.</summary>");
        sb.AppendLine($"{indent2}public {model.TypeName}()");
        sb.AppendLine($"{indent2}{{");
        sb.AppendLine($"{indent3}_items = null;");
        sb.AppendLine($"{indent3}_pool = ArrayPool<{T}>.Shared;");
        sb.AppendLine($"{indent3}_count = 0;");
        sb.AppendLine($"{indent2}}}");
        sb.AppendLine();

        // Capacity constructor
        sb.AppendLine($"{indent2}/// <summary>Creates a new pooled collection with the specified initial capacity.</summary>");
        sb.AppendLine($"{indent2}public {model.TypeName}(int capacity) : this(capacity, ArrayPool<{T}>.Shared) {{ }}");
        sb.AppendLine();

        // Capacity + pool constructor
        sb.AppendLine($"{indent2}/// <summary>Creates a new pooled collection with the specified initial capacity and pool.</summary>");
        sb.AppendLine($"{indent2}public {model.TypeName}(int capacity, ArrayPool<{T}> pool)");
        sb.AppendLine($"{indent2}{{");
        sb.AppendLine($"{indent3}_pool = pool ?? throw new ArgumentNullException(nameof(pool));");
        sb.AppendLine($"{indent3}_items = capacity > 0 ? pool.Rent(capacity) : null;");
        sb.AppendLine($"{indent3}_count = 0;");
        sb.AppendLine($"{indent2}}}");
        sb.AppendLine();

        // Count
        sb.AppendLine($"{indent2}/// <summary>Gets the number of elements.</summary>");
        sb.AppendLine($"{indent2}public {readonlyMod}int Count");
        sb.AppendLine($"{indent2}{{");
        sb.AppendLine($"{indent3}[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent3}get => _count;");
        sb.AppendLine($"{indent2}}}");
        sb.AppendLine();

        // Add
        sb.AppendLine($"{indent2}/// <summary>Appends an item to the collection.</summary>");
        sb.AppendLine($"{indent2}[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent2}public void Add({T} item)");
        sb.AppendLine($"{indent2}{{");
        sb.AppendLine($"{indent3}var items = _items;");
        sb.AppendLine($"{indent3}var count = _count;");
        sb.AppendLine($"{indent3}if (items is null || (uint)count >= (uint)items.Length)");
        sb.AppendLine($"{indent3}{{");
        sb.AppendLine($"{indent4}Grow();");
        sb.AppendLine($"{indent4}items = _items;");
        sb.AppendLine($"{indent3}}}");
        sb.AppendLine($"{indent3}items![count] = item;");
        sb.AppendLine($"{indent3}_count = count + 1;");
        sb.AppendLine($"{indent2}}}");
        sb.AppendLine();

        // Indexer
        sb.AppendLine($"{indent2}/// <summary>Gets the element at the specified index.</summary>");
        sb.AppendLine($"{indent2}public {readonlyMod}{T} this[int index]");
        sb.AppendLine($"{indent2}{{");
        sb.AppendLine($"{indent3}[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent3}get");
        sb.AppendLine($"{indent3}{{");
        sb.AppendLine($"{indent4}if ((uint)index >= (uint)_count) throw new ArgumentOutOfRangeException(nameof(index));");
        sb.AppendLine($"{indent4}return _items![index];");
        sb.AppendLine($"{indent3}}}");
        sb.AppendLine($"{indent2}}}");
        sb.AppendLine();

        // Dispose
        sb.AppendLine($"{indent2}/// <summary>Returns the rented buffer to the pool.</summary>");
        sb.AppendLine($"{indent2}public void Dispose()");
        sb.AppendLine($"{indent2}{{");
        sb.AppendLine($"{indent3}var items = _items;");
        sb.AppendLine($"{indent3}if (items is not null)");
        sb.AppendLine($"{indent3}{{");
        sb.AppendLine($"{indent4}_items = null;");
        sb.AppendLine($"{indent4}_count = 0;");
        sb.AppendLine($"{indent4}var pool = _pool ?? ArrayPool<{T}>.Shared;");
        sb.AppendLine($"{indent4}pool.Return(items, clearArray: RuntimeHelpers.IsReferenceOrContainsReferences<{T}>());");
        sb.AppendLine($"{indent3}}}");
        sb.AppendLine($"{indent2}}}");
        sb.AppendLine();

        // Grow
        sb.AppendLine($"{indent2}private void Grow()");
        sb.AppendLine($"{indent2}{{");
        sb.AppendLine($"{indent3}int newCapacity = _items is null ? DefaultCapacity : _items.Length * 2;");
        sb.AppendLine($"{indent3}var pool = _pool ?? ArrayPool<{T}>.Shared;");
        sb.AppendLine($"{indent3}var newItems = pool.Rent(newCapacity);");
        sb.AppendLine($"{indent3}if (_items is not null)");
        sb.AppendLine($"{indent3}{{");
        sb.AppendLine($"{indent4}Array.Copy(_items, 0, newItems, 0, _count);");
        sb.AppendLine($"{indent4}pool.Return(_items, clearArray: RuntimeHelpers.IsReferenceOrContainsReferences<{T}>());");
        sb.AppendLine($"{indent3}}}");
        sb.AppendLine($"{indent3}_items = newItems;");
        sb.AppendLine($"{indent2}}}");
        sb.AppendLine();

        // GetEnumerator
        sb.AppendLine($"{indent2}/// <summary>Returns an enumerator.</summary>");
        sb.AppendLine($"{indent2}[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent2}public {readonlyMod}Enumerator GetEnumerator() => new Enumerator(_items, _count);");
        sb.AppendLine();

        // Nested Enumerator
        sb.AppendLine($"{indent2}/// <summary>Enumerates the elements.</summary>");
        sb.AppendLine($"{indent2}public ref struct Enumerator");
        sb.AppendLine($"{indent2}{{");
        sb.AppendLine($"{indent3}private readonly {T}[]? _items;");
        sb.AppendLine($"{indent3}private readonly int _count;");
        sb.AppendLine($"{indent3}private int _index;");
        sb.AppendLine();
        sb.AppendLine($"{indent3}[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent3}internal Enumerator({T}[]? items, int count)");
        sb.AppendLine($"{indent3}{{");
        sb.AppendLine($"{indent4}_items = items;");
        sb.AppendLine($"{indent4}_count = count;");
        sb.AppendLine($"{indent4}_index = -1;");
        sb.AppendLine($"{indent3}}}");
        sb.AppendLine();
        sb.AppendLine($"{indent3}/// <summary>Gets the current element.</summary>");
        sb.AppendLine($"{indent3}public readonly ref readonly {T} Current");
        sb.AppendLine($"{indent3}{{");
        sb.AppendLine($"{indent4}[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent4}get => ref _items![_index];");
        sb.AppendLine($"{indent3}}}");
        sb.AppendLine();
        sb.AppendLine($"{indent3}/// <summary>Advances the enumerator.</summary>");
        sb.AppendLine($"{indent3}[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent3}public bool MoveNext()");
        sb.AppendLine($"{indent3}{{");
        sb.AppendLine($"{indent4}int index = _index + 1;");
        sb.AppendLine($"{indent4}if (index < _count)");
        sb.AppendLine($"{indent4}{{");
        sb.AppendLine($"{indent4}    _index = index;");
        sb.AppendLine($"{indent4}    return true;");
        sb.AppendLine($"{indent4}}}");
        sb.AppendLine($"{indent4}return false;");
        sb.AppendLine($"{indent3}}}");
        sb.AppendLine($"{indent2}}}");

        sb.AppendLine($"{indent}}}");

        if (model.Namespace is not null)
        {
            sb.AppendLine("}");
        }

        spc.AddSource($"{model.TypeName}.PooledCollection.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private readonly record struct GeneratorModel(
        string? Namespace,
        string TypeName,
        string ElementTypeFullName,
        bool IsStruct,
        Accessibility Accessibility);
}
