using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ZeroAlloc.Collections.Generators;

[Generator]
public sealed class ZeroAllocListGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "ZeroAlloc.Collections.ZeroAllocListAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targets = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeFullName,
            predicate: static (node, _) => node is TypeDeclarationSyntax,
            transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!.Value);

        context.RegisterSourceOutput(targets, static (spc, model) => Execute(spc, model));
    }

    private static GeneratorModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        var typeSymbol = (INamedTypeSymbol)ctx.TargetSymbol;
        var attr = ctx.Attributes.FirstOrDefault(a =>
            a.AttributeClass?.ToDisplayString() == AttributeFullName);

        if (attr is null || attr.ConstructorArguments.Length == 0)
            return null;

        var elementType = attr.ConstructorArguments[0].Value as INamedTypeSymbol;
        if (elementType is null)
            return null;

        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : typeSymbol.ContainingNamespace.ToDisplayString();

        return new GeneratorModel(
            Namespace: ns,
            TypeName: typeSymbol.Name,
            ElementTypeFullName: elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            ElementTypeShortName: elementType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat),
            IsStruct: typeSymbol.IsValueType,
            Accessibility: typeSymbol.DeclaredAccessibility);
    }

    private static void Execute(SourceProductionContext spc, GeneratorModel model)
    {
        var accessibility = model.Accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Private => "private",
            _ => "internal"
        };

        var typeKind = model.IsStruct ? "struct" : "class";
        var readonlyMod = model.IsStruct ? "readonly " : "";
        var T = model.ElementTypeFullName;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");
        }

        var indent = model.Namespace is not null ? "    " : "";
        var indent2 = indent + "    ";
        var indent3 = indent2 + "    ";
        var indent4 = indent3 + "    ";

        sb.AppendLine($"{indent}{accessibility} partial {typeKind} {model.TypeName} : System.IDisposable");
        sb.AppendLine($"{indent}{{");

        // Fields
        sb.AppendLine($"{indent2}private {T}[]? _array;");
        sb.AppendLine($"{indent2}private int _count;");
        sb.AppendLine($"{indent2}private ArrayPool<{T}>? _pool;");
        sb.AppendLine();
        sb.AppendLine($"{indent2}private const int DefaultCapacity = 4;");
        sb.AppendLine();

        // Default constructor
        sb.AppendLine($"{indent2}/// <summary>Creates a new empty list using the shared pool.</summary>");
        sb.AppendLine($"{indent2}public {model.TypeName}()");
        sb.AppendLine($"{indent2}{{");
        sb.AppendLine($"{indent3}_array = null;");
        sb.AppendLine($"{indent3}_pool = ArrayPool<{T}>.Shared;");
        sb.AppendLine($"{indent3}_count = 0;");
        sb.AppendLine($"{indent2}}}");
        sb.AppendLine();

        // Capacity constructor
        sb.AppendLine($"{indent2}/// <summary>Creates a new list with the specified initial capacity.</summary>");
        sb.AppendLine($"{indent2}public {model.TypeName}(int capacity) : this(capacity, ArrayPool<{T}>.Shared) {{ }}");
        sb.AppendLine();

        // Capacity + pool constructor
        sb.AppendLine($"{indent2}/// <summary>Creates a new list with the specified initial capacity and pool.</summary>");
        sb.AppendLine($"{indent2}public {model.TypeName}(int capacity, ArrayPool<{T}> pool)");
        sb.AppendLine($"{indent2}{{");
        sb.AppendLine($"{indent3}_pool = pool ?? throw new ArgumentNullException(nameof(pool));");
        sb.AppendLine($"{indent3}_array = capacity > 0 ? pool.Rent(capacity) : null;");
        sb.AppendLine($"{indent3}_count = 0;");
        sb.AppendLine($"{indent2}}}");
        sb.AppendLine();

        // Count
        sb.AppendLine($"{indent2}/// <summary>Gets the number of elements.</summary>");
        sb.AppendLine($"{indent2}public {readonlyMod}int Count");
        sb.AppendLine($"{indent2}{{");
        sb.AppendLine($"{indent3}[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent3}get => _count;");
        sb.AppendLine($"{indent2}}}");
        sb.AppendLine();

        // Indexer
        sb.AppendLine($"{indent2}/// <summary>Gets the element at the specified index.</summary>");
        sb.AppendLine($"{indent2}public {readonlyMod}{T} this[int index]");
        sb.AppendLine($"{indent2}{{");
        sb.AppendLine($"{indent3}[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent3}get");
        sb.AppendLine($"{indent3}{{");
        sb.AppendLine($"{indent4}if ((uint)index >= (uint)_count) throw new ArgumentOutOfRangeException(nameof(index));");
        sb.AppendLine($"{indent4}return _array![index];");
        sb.AppendLine($"{indent3}}}");
        sb.AppendLine($"{indent2}}}");
        sb.AppendLine();

        // Add
        sb.AppendLine($"{indent2}/// <summary>Appends an item to the end of the list.</summary>");
        sb.AppendLine($"{indent2}[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent2}public void Add({T} item)");
        sb.AppendLine($"{indent2}{{");
        sb.AppendLine($"{indent3}var array = _array;");
        sb.AppendLine($"{indent3}var count = _count;");
        sb.AppendLine($"{indent3}if (array is null || (uint)count >= (uint)array.Length)");
        sb.AppendLine($"{indent3}{{");
        sb.AppendLine($"{indent4}Grow();");
        sb.AppendLine($"{indent4}array = _array;");
        sb.AppendLine($"{indent3}}}");
        sb.AppendLine($"{indent3}array![count] = item;");
        sb.AppendLine($"{indent3}_count = count + 1;");
        sb.AppendLine($"{indent2}}}");
        sb.AppendLine();

        // AsSpan
        sb.AppendLine($"{indent2}/// <summary>Returns a span over the active elements.</summary>");
        sb.AppendLine($"{indent2}[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent2}public {readonlyMod}Span<{T}> AsSpan()");
        sb.AppendLine($"{indent2}{{");
        sb.AppendLine($"{indent3}return _array is null ? Span<{T}>.Empty : _array.AsSpan(0, _count);");
        sb.AppendLine($"{indent2}}}");
        sb.AppendLine();

        // AsReadOnlySpan
        sb.AppendLine($"{indent2}/// <summary>Returns a read-only span over the active elements.</summary>");
        sb.AppendLine($"{indent2}[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent2}public {readonlyMod}ReadOnlySpan<{T}> AsReadOnlySpan()");
        sb.AppendLine($"{indent2}{{");
        sb.AppendLine($"{indent3}return _array is null ? ReadOnlySpan<{T}>.Empty : new ReadOnlySpan<{T}>(_array, 0, _count);");
        sb.AppendLine($"{indent2}}}");
        sb.AppendLine();

        // Clear
        sb.AppendLine($"{indent2}/// <summary>Resets the count to zero.</summary>");
        sb.AppendLine($"{indent2}public void Clear()");
        sb.AppendLine($"{indent2}{{");
        sb.AppendLine($"{indent3}if (RuntimeHelpers.IsReferenceOrContainsReferences<{T}>() && _array is not null)");
        sb.AppendLine($"{indent3}{{");
        sb.AppendLine($"{indent4}Array.Clear(_array, 0, _count);");
        sb.AppendLine($"{indent3}}}");
        sb.AppendLine($"{indent3}_count = 0;");
        sb.AppendLine($"{indent2}}}");
        sb.AppendLine();

        // ToArray
        sb.AppendLine($"{indent2}/// <summary>Copies the active elements to a new array.</summary>");
        sb.AppendLine($"{indent2}public {readonlyMod}{T}[] ToArray()");
        sb.AppendLine($"{indent2}{{");
        sb.AppendLine($"{indent3}if (_count == 0) return Array.Empty<{T}>();");
        sb.AppendLine($"{indent3}var result = new {T}[_count];");
        sb.AppendLine($"{indent3}Array.Copy(_array!, 0, result, 0, _count);");
        sb.AppendLine($"{indent3}return result;");
        sb.AppendLine($"{indent2}}}");
        sb.AppendLine();

        // Dispose
        sb.AppendLine($"{indent2}/// <summary>Returns the rented buffer to the pool.</summary>");
        sb.AppendLine($"{indent2}public void Dispose()");
        sb.AppendLine($"{indent2}{{");
        sb.AppendLine($"{indent3}var array = _array;");
        sb.AppendLine($"{indent3}if (array is not null)");
        sb.AppendLine($"{indent3}{{");
        sb.AppendLine($"{indent4}_array = null;");
        sb.AppendLine($"{indent4}_count = 0;");
        sb.AppendLine($"{indent4}var pool = _pool ?? ArrayPool<{T}>.Shared;");
        sb.AppendLine($"{indent4}pool.Return(array, clearArray: RuntimeHelpers.IsReferenceOrContainsReferences<{T}>());");
        sb.AppendLine($"{indent3}}}");
        sb.AppendLine($"{indent2}}}");
        sb.AppendLine();

        // Grow
        sb.AppendLine($"{indent2}private void Grow()");
        sb.AppendLine($"{indent2}{{");
        sb.AppendLine($"{indent3}int newCapacity = _array is null ? DefaultCapacity : _array.Length * 2;");
        sb.AppendLine($"{indent3}var pool = _pool ?? ArrayPool<{T}>.Shared;");
        sb.AppendLine($"{indent3}var newArray = pool.Rent(newCapacity);");
        sb.AppendLine($"{indent3}if (_array is not null)");
        sb.AppendLine($"{indent3}{{");
        sb.AppendLine($"{indent4}Array.Copy(_array, 0, newArray, 0, _count);");
        sb.AppendLine($"{indent4}pool.Return(_array, clearArray: RuntimeHelpers.IsReferenceOrContainsReferences<{T}>());");
        sb.AppendLine($"{indent3}}}");
        sb.AppendLine($"{indent3}_array = newArray;");
        sb.AppendLine($"{indent2}}}");
        sb.AppendLine();

        // GetEnumerator
        sb.AppendLine($"{indent2}/// <summary>Returns an enumerator that iterates through the list.</summary>");
        sb.AppendLine($"{indent2}[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent2}public {readonlyMod}Enumerator GetEnumerator() => new Enumerator(_array, _count);");
        sb.AppendLine();

        // Nested Enumerator
        sb.AppendLine($"{indent2}/// <summary>Enumerates the elements.</summary>");
        sb.AppendLine($"{indent2}public ref struct Enumerator");
        sb.AppendLine($"{indent2}{{");
        sb.AppendLine($"{indent3}private readonly {T}[]? _items;");
        sb.AppendLine($"{indent3}private readonly int _count;");
        sb.AppendLine($"{indent3}private int _index;");
        sb.AppendLine();
        sb.AppendLine($"{indent3}[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent3}internal Enumerator({T}[]? items, int count)");
        sb.AppendLine($"{indent3}{{");
        sb.AppendLine($"{indent4}_items = items;");
        sb.AppendLine($"{indent4}_count = count;");
        sb.AppendLine($"{indent4}_index = -1;");
        sb.AppendLine($"{indent3}}}");
        sb.AppendLine();
        sb.AppendLine($"{indent3}/// <summary>Gets the current element.</summary>");
        sb.AppendLine($"{indent3}public readonly ref readonly {T} Current");
        sb.AppendLine($"{indent3}{{");
        sb.AppendLine($"{indent4}[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent4}get => ref _items![_index];");
        sb.AppendLine($"{indent3}}}");
        sb.AppendLine();
        sb.AppendLine($"{indent3}/// <summary>Advances the enumerator.</summary>");
        sb.AppendLine($"{indent3}[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent3}public bool MoveNext()");
        sb.AppendLine($"{indent3}{{");
        sb.AppendLine($"{indent4}int index = _index + 1;");
        sb.AppendLine($"{indent4}if (index < _count)");
        sb.AppendLine($"{indent4}{{");
        sb.AppendLine($"{indent4}    _index = index;");
        sb.AppendLine($"{indent4}    return true;");
        sb.AppendLine($"{indent4}}}");
        sb.AppendLine($"{indent4}return false;");
        sb.AppendLine($"{indent3}}}");
        sb.AppendLine($"{indent2}}}");

        sb.AppendLine($"{indent}}}");

        if (model.Namespace is not null)
        {
            sb.AppendLine("}");
        }

        spc.AddSource($"{model.TypeName}.ZeroAllocList.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private readonly record struct GeneratorModel(
        string? Namespace,
        string TypeName,
        string ElementTypeFullName,
        string ElementTypeShortName,
        bool IsStruct,
        Accessibility Accessibility);
}
