using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ZeroAlloc.Collections.Generators;

[Generator]
public sealed class ZeroAllocEnumerableGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "ZeroAlloc.Collections.ZeroAllocEnumerableAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targets = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeFullName,
            predicate: static (node, _) => node is TypeDeclarationSyntax,
            transform: static (ctx, _) => GetModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!.Value);

        context.RegisterSourceOutput(targets, static (spc, model) => Execute(spc, model));
    }

    private static GeneratorModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        var typeSymbol = (INamedTypeSymbol)ctx.TargetSymbol;

        // Find the array field and count field
        string? arrayFieldName = null;
        string? arrayElementType = null;
        string? countFieldName = null;

        foreach (var member in typeSymbol.GetMembers())
        {
            if (member is IFieldSymbol field && !field.IsStatic)
            {
                if (field.Type is IArrayTypeSymbol arrayType && arrayFieldName is null)
                {
                    arrayFieldName = field.Name;
                    arrayElementType = arrayType.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                }
                else if (field.Type.SpecialType == SpecialType.System_Int32 && countFieldName is null)
                {
                    countFieldName = field.Name;
                }
            }
        }

        if (arrayFieldName is null || arrayElementType is null || countFieldName is null)
            return null;

        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : typeSymbol.ContainingNamespace.ToDisplayString();

        return new GeneratorModel(
            Namespace: ns,
            TypeName: typeSymbol.Name,
            ArrayFieldName: arrayFieldName,
            CountFieldName: countFieldName,
            ElementTypeFullName: arrayElementType,
            IsStruct: typeSymbol.IsValueType,
            Accessibility: typeSymbol.DeclaredAccessibility);
    }

    private static void Execute(SourceProductionContext spc, GeneratorModel model)
    {
        var accessibility = model.Accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Private => "private",
            _ => "internal"
        };

        var typeKind = model.IsStruct ? "struct" : "class";
        var readonlyMod = model.IsStruct ? "readonly " : "";
        var T = model.ElementTypeFullName;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");
        }

        var indent = model.Namespace is not null ? "    " : "";
        var indent2 = indent + "    ";
        var indent3 = indent2 + "    ";
        var indent4 = indent3 + "    ";

        sb.AppendLine($"{indent}{accessibility} partial {typeKind} {model.TypeName}");
        sb.AppendLine($"{indent}{{");

        // GetEnumerator
        sb.AppendLine($"{indent2}/// <summary>Returns an enumerator that iterates through the collection.</summary>");
        sb.AppendLine($"{indent2}[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent2}public {readonlyMod}Enumerator GetEnumerator() => new Enumerator({model.ArrayFieldName}, {model.CountFieldName});");
        sb.AppendLine();

        // Nested Enumerator
        sb.AppendLine($"{indent2}/// <summary>Enumerates the elements.</summary>");
        sb.AppendLine($"{indent2}public ref struct Enumerator");
        sb.AppendLine($"{indent2}{{");
        sb.AppendLine($"{indent3}private readonly {T}[]? _items;");
        sb.AppendLine($"{indent3}private readonly int _count;");
        sb.AppendLine($"{indent3}private int _index;");
        sb.AppendLine();
        sb.AppendLine($"{indent3}[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent3}internal Enumerator({T}[]? items, int count)");
        sb.AppendLine($"{indent3}{{");
        sb.AppendLine($"{indent4}_items = items;");
        sb.AppendLine($"{indent4}_count = count;");
        sb.AppendLine($"{indent4}_index = -1;");
        sb.AppendLine($"{indent3}}}");
        sb.AppendLine();
        sb.AppendLine($"{indent3}/// <summary>Gets the current element.</summary>");
        sb.AppendLine($"{indent3}public readonly ref readonly {T} Current");
        sb.AppendLine($"{indent3}{{");
        sb.AppendLine($"{indent4}[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent4}get => ref _items![_index];");
        sb.AppendLine($"{indent3}}}");
        sb.AppendLine();
        sb.AppendLine($"{indent3}/// <summary>Advances the enumerator.</summary>");
        sb.AppendLine($"{indent3}[MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent3}public bool MoveNext()");
        sb.AppendLine($"{indent3}{{");
        sb.AppendLine($"{indent4}int index = _index + 1;");
        sb.AppendLine($"{indent4}if (index < _count)");
        sb.AppendLine($"{indent4}{{");
        sb.AppendLine($"{indent4}    _index = index;");
        sb.AppendLine($"{indent4}    return true;");
        sb.AppendLine($"{indent4}}}");
        sb.AppendLine($"{indent4}return false;");
        sb.AppendLine($"{indent3}}}");
        sb.AppendLine($"{indent2}}}");

        sb.AppendLine($"{indent}}}");

        if (model.Namespace is not null)
        {
            sb.AppendLine("}");
        }

        spc.AddSource($"{model.TypeName}.ZeroAllocEnumerable.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private readonly record struct GeneratorModel(
        string? Namespace,
        string TypeName,
        string ArrayFieldName,
        string CountFieldName,
        string ElementTypeFullName,
        bool IsStruct,
        Accessibility Accessibility);
}
